### ISSUE TITLE
Editing shift

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmhc-homebase#5]
I am trying to move a shift (giving it a new end time), and I'm getting the following error: Invalid argument for dbDates->select_dbDates call =15-10-04
Could be user error, of course . . . 
Thank you!!

**Comment by megandalster** [comment]
Moving a shift should now work when Dave replaces the scripts that I just sent him.  Check it out and let me know.  Allen

**Comment by gnoonan** [comment]
Nope.  I still get Invalid argument for dbDates->select_dbDates call =15-10-04 when I try to move the shift.

**Comment by megandalster** [comment]
Try again and let me know if it works.  Thanks.  Allen

**Comment by gnoonan** [comment]
It works!  Thank you Allen!
