### ISSUE TITLE
Master schedule

### ISSUE THREAD

**Issue by gnoonan** [megandalster/rmhc-homebase#6]
I am trying to edit the master schedule, and when I click on odd Fridays 12-3, I get a 404 error code.  I could've sworn I messed around with editing the master schedule when we were test-driving this thing?  If I somehow missed this issue earlier, apologies!

**Comment by megandalster** [comment]
This one should be fixed by the changes Scott made to the web site a few minutes ago.  Check it out and let me know.

**Comment by gnoonan** [comment]
I am still getting a "page not found"?  I have logged out and logged back in, in case that was necessary for the changes Scott made to be functional.
